# Site settings
title: OSLH
email: oslh@googlegroups.com
description: OpenSource Lab of HEU
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://oslh.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

