# Site settings
title: OSLH
email: oslh@googlegroups.com
permalink: /:year/:title/
paginate: 10
exclude: []
baseurl: /jekyll-bootstrap
description: OpenSource Lab of HEU
url: "http://oslh.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown


